Internal Server Error: /student/class/
Traceback (most recent call last):
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/michaelwan/Desktop/Projects/Heroku/Django/CalTutors/student/views.py", line 689, in class_view
    return render(request, 'student/course.html', data)
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/template/base.py", line 208, in render
    return self._render(context)
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/template/defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/template/defaulttags.py", line 315, in render
    return nodelist.render(context)
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/template/defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/template/defaulttags.py", line 508, in render
    six.iteritems(self.extra_context)}
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/template/defaulttags.py", line 507, in <dictcomp>
    values = {key: val.resolve(context) for key, val in
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/template/base.py", line 739, in resolve
    new_obj = func(obj, *arg_vals)
  File "/Users/michaelwan/Desktop/Projects/Heroku/Django/CalTutors/student/templatetags/student_extras.py", line 28, in key
    return d[key_name]
TypeError: string indices must be integers
Internal Server Error: /student/class/
Traceback (most recent call last):
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/michaelwan/Desktop/Projects/Heroku/Django/CalTutors/student/views.py", line 689, in class_view
    return render(request, 'student/course.html', data)
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/template/loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/template/backends/django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/template/engine.py", line 160, in get_template
    template, origin = self.find_template(template_name)
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/template/engine.py", line 134, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/template/base.py", line 233, in compile_nodelist
    return parser.parse()
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
TemplateSyntaxError: Could not parse some characters: |{questions||key:l|key:i|key:'prompt'|safe
Internal Server Error: /student/class/
Traceback (most recent call last):
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/michaelwan/Desktop/Projects/Heroku/Django/CalTutors/student/views.py", line 689, in class_view
    return render(request, 'student/course.html', data)
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/template/loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/template/backends/django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/template/engine.py", line 160, in get_template
    template, origin = self.find_template(template_name)
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/template/engine.py", line 134, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/template/base.py", line 233, in compile_nodelist
    return parser.parse()
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
TemplateSyntaxError: Unclosed tag on line 189: 'for'. Looking for one of: empty, endfor.
Internal Server Error: /student/class/
Traceback (most recent call last):
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/michaelwan/Desktop/Projects/Heroku/Django/CalTutors/student/views.py", line 689, in class_view
    return render(request, 'student/course.html', data)
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/template/base.py", line 208, in render
    return self._render(context)
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/templatetags/static.py", line 104, in render
    url = self.url(context)
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/templatetags/static.py", line 101, in url
    return self.handle_simple(path)
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/templatetags/static.py", line 114, in handle_simple
    return staticfiles_storage.url(path)
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/contrib/staticfiles/storage.py", line 132, in url
    hashed_name = self.stored_name(clean_name)
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/contrib/staticfiles/storage.py", line 292, in stored_name
    cache_name = self.clean_name(self.hashed_name(name))
  File "/Users/michaelwan/miniconda2/lib/python2.7/site-packages/django/contrib/staticfiles/storage.py", line 95, in hashed_name
    (clean_name, self))
ValueError: The file 'jsMath/jsMath.js' could not be found with <whitenoise.storage.CompressedManifestStaticFilesStorage object at 0x103e76c10>.
Internal Server Error: /
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 111, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/anaconda3/lib/python3.6/site-packages/django/urls/resolvers.py", line 491, in resolve
    for pattern in self.url_patterns:
  File "/anaconda3/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/anaconda3/lib/python3.6/site-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/anaconda3/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/anaconda3/lib/python3.6/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/michaelwan/Desktop/CS/Misc. Projects/Heroku/caltutors/CalTutors/urls.py", line 24, in <module>
    url(r'^student/', include('student.urls')),
  File "/anaconda3/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/michaelwan/Desktop/CS/Misc. Projects/Heroku/caltutors/student/urls.py", line 3, in <module>
    from . import views
  File "/Users/michaelwan/Desktop/CS/Misc. Projects/Heroku/caltutors/student/views.py", line 210
    print returned
                 ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(returned)?
Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 111, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/anaconda3/lib/python3.6/site-packages/django/urls/resolvers.py", line 491, in resolve
    for pattern in self.url_patterns:
  File "/anaconda3/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/anaconda3/lib/python3.6/site-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/anaconda3/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/anaconda3/lib/python3.6/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/michaelwan/Desktop/CS/Misc. Projects/Heroku/caltutors/CalTutors/urls.py", line 24, in <module>
    url(r'^student/', include('student.urls')),
  File "/anaconda3/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/michaelwan/Desktop/CS/Misc. Projects/Heroku/caltutors/student/urls.py", line 3, in <module>
    from . import views
  File "/Users/michaelwan/Desktop/CS/Misc. Projects/Heroku/caltutors/student/views.py", line 210
    print returned
                 ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(returned)?
Internal Server Error: /
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 111, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/anaconda3/lib/python3.6/site-packages/django/urls/resolvers.py", line 491, in resolve
    for pattern in self.url_patterns:
  File "/anaconda3/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/anaconda3/lib/python3.6/site-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/anaconda3/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/anaconda3/lib/python3.6/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/michaelwan/Desktop/CS/Misc. Projects/Heroku/caltutors/CalTutors/urls.py", line 24, in <module>
    url(r'^student/', include('student.urls')),
  File "/anaconda3/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/michaelwan/Desktop/CS/Misc. Projects/Heroku/caltutors/student/urls.py", line 3, in <module>
    from . import views
  File "/Users/michaelwan/Desktop/CS/Misc. Projects/Heroku/caltutors/student/views.py", line 411
    print "*** Error: Student DNE"
                                 ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("*** Error: Student DNE")?
Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 111, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/anaconda3/lib/python3.6/site-packages/django/urls/resolvers.py", line 491, in resolve
    for pattern in self.url_patterns:
  File "/anaconda3/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/anaconda3/lib/python3.6/site-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/anaconda3/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/anaconda3/lib/python3.6/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/michaelwan/Desktop/CS/Misc. Projects/Heroku/caltutors/CalTutors/urls.py", line 24, in <module>
    url(r'^student/', include('student.urls')),
  File "/anaconda3/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/michaelwan/Desktop/CS/Misc. Projects/Heroku/caltutors/student/urls.py", line 3, in <module>
    from . import views
  File "/Users/michaelwan/Desktop/CS/Misc. Projects/Heroku/caltutors/student/views.py", line 411
    print "*** Error: Student DNE"
                                 ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("*** Error: Student DNE")?
Internal Server Error: /
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 111, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/anaconda3/lib/python3.6/site-packages/django/urls/resolvers.py", line 491, in resolve
    for pattern in self.url_patterns:
  File "/anaconda3/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/anaconda3/lib/python3.6/site-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/anaconda3/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/anaconda3/lib/python3.6/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/michaelwan/Desktop/CS/Misc. Projects/Heroku/caltutors/CalTutors/urls.py", line 24, in <module>
    url(r'^student/', include('student.urls')),
  File "/anaconda3/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/michaelwan/Desktop/CS/Misc. Projects/Heroku/caltutors/student/urls.py", line 3, in <module>
    from . import views
  File "/Users/michaelwan/Desktop/CS/Misc. Projects/Heroku/caltutors/student/views.py", line 10, in <module>
    from django.core.urlresolvers import reverse
ModuleNotFoundError: No module named 'django.core.urlresolvers'
Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 111, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/anaconda3/lib/python3.6/site-packages/django/urls/resolvers.py", line 491, in resolve
    for pattern in self.url_patterns:
  File "/anaconda3/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/anaconda3/lib/python3.6/site-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/anaconda3/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/anaconda3/lib/python3.6/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/michaelwan/Desktop/CS/Misc. Projects/Heroku/caltutors/CalTutors/urls.py", line 24, in <module>
    url(r'^student/', include('student.urls')),
  File "/anaconda3/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/michaelwan/Desktop/CS/Misc. Projects/Heroku/caltutors/student/urls.py", line 3, in <module>
    from . import views
  File "/Users/michaelwan/Desktop/CS/Misc. Projects/Heroku/caltutors/student/views.py", line 10, in <module>
    from django.core.urlresolvers import reverse
ModuleNotFoundError: No module named 'django.core.urlresolvers'
Internal Server Error: /
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 111, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/anaconda3/lib/python3.6/site-packages/django/urls/resolvers.py", line 491, in resolve
    for pattern in self.url_patterns:
  File "/anaconda3/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/anaconda3/lib/python3.6/site-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/anaconda3/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/anaconda3/lib/python3.6/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/michaelwan/Desktop/CS/Misc. Projects/Heroku/caltutors/CalTutors/urls.py", line 24, in <module>
    url(r'^student/', include('student.urls')),
  File "/anaconda3/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/michaelwan/Desktop/CS/Misc. Projects/Heroku/caltutors/student/urls.py", line 3, in <module>
    from . import views
  File "/Users/michaelwan/Desktop/CS/Misc. Projects/Heroku/caltutors/student/views.py", line 18, in <module>
    import base64, datetime, random, string, time, commands, json
ModuleNotFoundError: No module named 'commands'
Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 111, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/anaconda3/lib/python3.6/site-packages/django/urls/resolvers.py", line 491, in resolve
    for pattern in self.url_patterns:
  File "/anaconda3/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/anaconda3/lib/python3.6/site-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/anaconda3/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/anaconda3/lib/python3.6/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/michaelwan/Desktop/CS/Misc. Projects/Heroku/caltutors/CalTutors/urls.py", line 24, in <module>
    url(r'^student/', include('student.urls')),
  File "/anaconda3/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/michaelwan/Desktop/CS/Misc. Projects/Heroku/caltutors/student/urls.py", line 3, in <module>
    from . import views
  File "/Users/michaelwan/Desktop/CS/Misc. Projects/Heroku/caltutors/student/views.py", line 18, in <module>
    import base64, datetime, random, string, time, commands, json
ModuleNotFoundError: No module named 'commands'
Internal Server Error: /
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 111, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/anaconda3/lib/python3.6/site-packages/django/urls/resolvers.py", line 491, in resolve
    for pattern in self.url_patterns:
  File "/anaconda3/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/anaconda3/lib/python3.6/site-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/anaconda3/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/anaconda3/lib/python3.6/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/michaelwan/Desktop/CS/Misc. Projects/Heroku/caltutors/CalTutors/urls.py", line 24, in <module>
    url(r'^student/', include('student.urls')),
  File "/anaconda3/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/michaelwan/Desktop/CS/Misc. Projects/Heroku/caltutors/student/urls.py", line 3, in <module>
    from . import views
  File "/Users/michaelwan/Desktop/CS/Misc. Projects/Heroku/caltutors/student/views.py", line 22, in <module>
    import gspread
ModuleNotFoundError: No module named 'gspread'
Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 111, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/anaconda3/lib/python3.6/site-packages/django/urls/resolvers.py", line 491, in resolve
    for pattern in self.url_patterns:
  File "/anaconda3/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/anaconda3/lib/python3.6/site-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/anaconda3/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/anaconda3/lib/python3.6/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/michaelwan/Desktop/CS/Misc. Projects/Heroku/caltutors/CalTutors/urls.py", line 24, in <module>
    url(r'^student/', include('student.urls')),
  File "/anaconda3/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/michaelwan/Desktop/CS/Misc. Projects/Heroku/caltutors/student/urls.py", line 3, in <module>
    from . import views
  File "/Users/michaelwan/Desktop/CS/Misc. Projects/Heroku/caltutors/student/views.py", line 22, in <module>
    import gspread
ModuleNotFoundError: No module named 'gspread'
Internal Server Error: /
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 111, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/anaconda3/lib/python3.6/site-packages/django/urls/resolvers.py", line 491, in resolve
    for pattern in self.url_patterns:
  File "/anaconda3/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/anaconda3/lib/python3.6/site-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/anaconda3/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/anaconda3/lib/python3.6/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/michaelwan/Desktop/CS/Misc. Projects/Heroku/caltutors/CalTutors/urls.py", line 24, in <module>
    url(r'^student/', include('student.urls')),
  File "/anaconda3/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/michaelwan/Desktop/CS/Misc. Projects/Heroku/caltutors/student/urls.py", line 3, in <module>
    from . import views
  File "/Users/michaelwan/Desktop/CS/Misc. Projects/Heroku/caltutors/student/views.py", line 23, in <module>
    from oauth2client.service_account import ServiceAccountCredentials
ModuleNotFoundError: No module named 'oauth2client'
Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 111, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/anaconda3/lib/python3.6/site-packages/django/urls/resolvers.py", line 491, in resolve
    for pattern in self.url_patterns:
  File "/anaconda3/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/anaconda3/lib/python3.6/site-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/anaconda3/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/anaconda3/lib/python3.6/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/michaelwan/Desktop/CS/Misc. Projects/Heroku/caltutors/CalTutors/urls.py", line 24, in <module>
    url(r'^student/', include('student.urls')),
  File "/anaconda3/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/michaelwan/Desktop/CS/Misc. Projects/Heroku/caltutors/student/urls.py", line 3, in <module>
    from . import views
  File "/Users/michaelwan/Desktop/CS/Misc. Projects/Heroku/caltutors/student/views.py", line 23, in <module>
    from oauth2client.service_account import ServiceAccountCredentials
ModuleNotFoundError: No module named 'oauth2client'
Internal Server Error: /
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 111, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/anaconda3/lib/python3.6/site-packages/django/urls/resolvers.py", line 491, in resolve
    for pattern in self.url_patterns:
  File "/anaconda3/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/anaconda3/lib/python3.6/site-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/anaconda3/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/anaconda3/lib/python3.6/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/michaelwan/Desktop/CS/Misc. Projects/Heroku/caltutors/CalTutors/urls.py", line 26, in <module>
    url(r'^', include('pages.urls')),
  File "/anaconda3/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/michaelwan/Desktop/CS/Misc. Projects/Heroku/caltutors/pages/urls.py", line 3, in <module>
    from . import views
  File "/Users/michaelwan/Desktop/CS/Misc. Projects/Heroku/caltutors/pages/views.py", line 12, in <module>
    from django.core.urlresolvers import reverse
ModuleNotFoundError: No module named 'django.core.urlresolvers'
Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 111, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/anaconda3/lib/python3.6/site-packages/django/urls/resolvers.py", line 491, in resolve
    for pattern in self.url_patterns:
  File "/anaconda3/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/anaconda3/lib/python3.6/site-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/anaconda3/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/anaconda3/lib/python3.6/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/michaelwan/Desktop/CS/Misc. Projects/Heroku/caltutors/CalTutors/urls.py", line 26, in <module>
    url(r'^', include('pages.urls')),
  File "/anaconda3/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/michaelwan/Desktop/CS/Misc. Projects/Heroku/caltutors/pages/urls.py", line 3, in <module>
    from . import views
  File "/Users/michaelwan/Desktop/CS/Misc. Projects/Heroku/caltutors/pages/views.py", line 12, in <module>
    from django.core.urlresolvers import reverse
ModuleNotFoundError: No module named 'django.core.urlresolvers'
Internal Server Error: /
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/michaelwan/Desktop/CS/Misc. Projects/Heroku/caltutors/pages/views.py", line 108, in index_view
    if request.user.is_authenticated():
AttributeError: 'WSGIRequest' object has no attribute 'user'
Internal Server Error: /
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/michaelwan/Desktop/CS/Misc. Projects/Heroku/caltutors/pages/views.py", line 108, in index_view
    if request.user.is_authenticated():
AttributeError: 'WSGIRequest' object has no attribute 'user'
Internal Server Error: /
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/michaelwan/Desktop/CS/Misc. Projects/Heroku/caltutors/pages/views.py", line 108, in index_view
    if request.user.is_authenticated():
AttributeError: 'WSGIRequest' object has no attribute 'user'
Internal Server Error: /
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/michaelwan/Desktop/CS/Misc. Projects/Heroku/caltutors/pages/views.py", line 108, in index_view
    if request.user.is_authenticated():
AttributeError: 'WSGIRequest' object has no attribute 'user'
Internal Server Error: /
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/michaelwan/Desktop/CS/Misc. Projects/Heroku/caltutors/pages/views.py", line 108, in index_view
    if request.user.is_authenticated():
TypeError: 'bool' object is not callable
Internal Server Error: /
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/michaelwan/Desktop/CS/Misc. Projects/Heroku/caltutors/pages/views.py", line 108, in index_view
    if request.user.is_authenticated:
TypeError: 'bool' object is not callable
Internal Server Error: /
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/michaelwan/Desktop/CS/Misc. Projects/Heroku/caltutors/pages/views.py", line 108, in index_view
    if request.user.is_authenticated:
TypeError: 'bool' object is not callable
Internal Server Error: /
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/michaelwan/Desktop/CS/Misc. Projects/Heroku/caltutors/pages/views.py", line 114, in index_view
    return render(request, 'pages/index.html', data)
  File "/anaconda3/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/anaconda3/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/anaconda3/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/anaconda3/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/anaconda3/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/anaconda3/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/anaconda3/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/anaconda3/lib/python3.6/site-packages/django/templatetags/static.py", line 106, in render
    url = self.url(context)
  File "/anaconda3/lib/python3.6/site-packages/django/templatetags/static.py", line 103, in url
    return self.handle_simple(path)
  File "/anaconda3/lib/python3.6/site-packages/django/templatetags/static.py", line 118, in handle_simple
    return staticfiles_storage.url(path)
  File "/anaconda3/lib/python3.6/site-packages/django/utils/functional.py", line 213, in inner
    self._setup()
  File "/anaconda3/lib/python3.6/site-packages/django/contrib/staticfiles/storage.py", line 491, in _setup
    self._wrapped = get_storage_class(settings.STATICFILES_STORAGE)()
  File "/anaconda3/lib/python3.6/site-packages/django/core/files/storage.py", line 356, in get_storage_class
    return import_string(import_path or settings.DEFAULT_FILE_STORAGE)
  File "/anaconda3/lib/python3.6/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/anaconda3/lib/python3.6/site-packages/whitenoise/django.py", line 2, in <module>
    '\n\n'
ImportError: 

Your WhiteNoise configuration is incompatible with WhiteNoise v4.0
This can be fixed by following the upgrade instructions at:
http://whitenoise.evans.io/en/stable/changelog.html#v4-0


Internal Server Error: /
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/michaelwan/Desktop/CS/Misc. Projects/Heroku/caltutors/pages/views.py", line 114, in index_view
    return render(request, 'pages/index.html', data)
  File "/anaconda3/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/anaconda3/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/anaconda3/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/anaconda3/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/anaconda3/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/anaconda3/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/anaconda3/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/anaconda3/lib/python3.6/site-packages/django/templatetags/static.py", line 106, in render
    url = self.url(context)
  File "/anaconda3/lib/python3.6/site-packages/django/templatetags/static.py", line 103, in url
    return self.handle_simple(path)
  File "/anaconda3/lib/python3.6/site-packages/django/templatetags/static.py", line 118, in handle_simple
    return staticfiles_storage.url(path)
  File "/anaconda3/lib/python3.6/site-packages/django/utils/functional.py", line 213, in inner
    self._setup()
  File "/anaconda3/lib/python3.6/site-packages/django/contrib/staticfiles/storage.py", line 491, in _setup
    self._wrapped = get_storage_class(settings.STATICFILES_STORAGE)()
  File "/anaconda3/lib/python3.6/site-packages/django/core/files/storage.py", line 356, in get_storage_class
    return import_string(import_path or settings.DEFAULT_FILE_STORAGE)
  File "/anaconda3/lib/python3.6/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/anaconda3/lib/python3.6/site-packages/whitenoise/django.py", line 2, in <module>
    '\n\n'
ImportError: 

Your WhiteNoise configuration is incompatible with WhiteNoise v4.0
This can be fixed by following the upgrade instructions at:
http://whitenoise.evans.io/en/stable/changelog.html#v4-0


Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/caltutors_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/anaconda3/envs/caltutors_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 111, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/anaconda3/envs/caltutors_env/lib/python3.6/site-packages/django/urls/resolvers.py", line 491, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/anaconda3/envs/caltutors_env/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/anaconda3/envs/caltutors_env/lib/python3.6/site-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/anaconda3/envs/caltutors_env/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/anaconda3/envs/caltutors_env/lib/python3.6/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/anaconda3/envs/caltutors_env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/tkkim/caltutors/CalTutors/urls.py", line 26, in <module>
    url(r'^', include('pages.urls')),
  File "/usr/local/anaconda3/envs/caltutors_env/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/anaconda3/envs/caltutors_env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/tkkim/caltutors/pages/urls.py", line 3, in <module>
    from . import views
  File "/Users/tkkim/caltutors/pages/views.py", line 57
    'abhinav_kommula': 'Abhinav Kommula'
                     ^
SyntaxError: invalid syntax
Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/caltutors_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/anaconda3/envs/caltutors_env/lib/python3.6/site-packages/django/utils/deprecation.py", line 90, in __call__
    response = self.process_request(request)
  File "/usr/local/anaconda3/envs/caltutors_env/lib/python3.6/site-packages/django/middleware/common.py", line 52, in process_request
    if self.should_redirect_with_slash(request):
  File "/usr/local/anaconda3/envs/caltutors_env/lib/python3.6/site-packages/django/middleware/common.py", line 70, in should_redirect_with_slash
    not is_valid_path(request.path_info, urlconf) and
  File "/usr/local/anaconda3/envs/caltutors_env/lib/python3.6/site-packages/django/urls/base.py", line 157, in is_valid_path
    resolve(path, urlconf)
  File "/usr/local/anaconda3/envs/caltutors_env/lib/python3.6/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/usr/local/anaconda3/envs/caltutors_env/lib/python3.6/site-packages/django/urls/resolvers.py", line 491, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/anaconda3/envs/caltutors_env/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/anaconda3/envs/caltutors_env/lib/python3.6/site-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/anaconda3/envs/caltutors_env/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/anaconda3/envs/caltutors_env/lib/python3.6/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/anaconda3/envs/caltutors_env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/tkkim/caltutors/CalTutors/urls.py", line 26, in <module>
    url(r'^', include('pages.urls')),
  File "/usr/local/anaconda3/envs/caltutors_env/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/anaconda3/envs/caltutors_env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/tkkim/caltutors/pages/urls.py", line 3, in <module>
    from . import views
  File "/Users/tkkim/caltutors/pages/views.py", line 57
    'abhinav_kommula': 'Abhinav Kommula'
                     ^
SyntaxError: invalid syntax
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/caltutors_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/anaconda3/envs/caltutors_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 111, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/anaconda3/envs/caltutors_env/lib/python3.6/site-packages/django/urls/resolvers.py", line 491, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/anaconda3/envs/caltutors_env/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/anaconda3/envs/caltutors_env/lib/python3.6/site-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/anaconda3/envs/caltutors_env/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/anaconda3/envs/caltutors_env/lib/python3.6/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/anaconda3/envs/caltutors_env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/tkkim/caltutors/CalTutors/urls.py", line 26, in <module>
    url(r'^', include('pages.urls')),
  File "/usr/local/anaconda3/envs/caltutors_env/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/anaconda3/envs/caltutors_env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/tkkim/caltutors/pages/urls.py", line 3, in <module>
    from . import views
  File "/Users/tkkim/caltutors/pages/views.py", line 93
    'abhinav_kommula': 'Vice President'
                     ^
SyntaxError: invalid syntax
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/caltutors_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/anaconda3/envs/caltutors_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 111, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/anaconda3/envs/caltutors_env/lib/python3.6/site-packages/django/urls/resolvers.py", line 491, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/anaconda3/envs/caltutors_env/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/anaconda3/envs/caltutors_env/lib/python3.6/site-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/anaconda3/envs/caltutors_env/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/anaconda3/envs/caltutors_env/lib/python3.6/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/anaconda3/envs/caltutors_env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/tkkim/caltutors/CalTutors/urls.py", line 26, in <module>
    url(r'^', include('pages.urls')),
  File "/usr/local/anaconda3/envs/caltutors_env/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/anaconda3/envs/caltutors_env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/tkkim/caltutors/pages/urls.py", line 3, in <module>
    from . import views
  File "/Users/tkkim/caltutors/pages/views.py", line 93
    'abhinav_kommula': 'Vice President'
                     ^
SyntaxError: invalid syntax
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/caltutors_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/anaconda3/envs/caltutors_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 111, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/anaconda3/envs/caltutors_env/lib/python3.6/site-packages/django/urls/resolvers.py", line 491, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/anaconda3/envs/caltutors_env/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/anaconda3/envs/caltutors_env/lib/python3.6/site-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/anaconda3/envs/caltutors_env/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/anaconda3/envs/caltutors_env/lib/python3.6/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/anaconda3/envs/caltutors_env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/tkkim/caltutors/CalTutors/urls.py", line 26, in <module>
    url(r'^', include('pages.urls')),
  File "/usr/local/anaconda3/envs/caltutors_env/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/anaconda3/envs/caltutors_env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/tkkim/caltutors/pages/urls.py", line 3, in <module>
    from . import views
  File "/Users/tkkim/caltutors/pages/views.py", line 129
    'abhinav_kommula': 'Abhinav is a senior at Monta Vista High School. He enjoys participating in the AMC Competitions since his freshman year in high school, and has qualified for AIME 3 times since then and made the Distinguished Honor Roll in 10th grade. He also enjoys programming in C++ and is in the Platinum division for USACO. During his free time, Abhinav enjoys cooking with his family and arguing with his friends over whether pineapple belongs on pizza.'
                     ^
SyntaxError: invalid syntax
